name: "Contribution Closed - Auto Triage"

on:
  workflow_call:

permissions:
  pull-requests: write
  issues: write

jobs:
  Triage:
    runs-on: ubuntu-latest
    name: Contribution by ${{github.actor}} - Auto Triage - ${{github.event_name}}
    steps:
        - name: ⚙️ Checkout Repo
          uses: actions/checkout@v4
          with:
            repository: SessionsBot/.github
            ref: main
            path: configRepo
            
        - name: 📋 End Triage
          uses: actions/github-script@v7
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            script: |
              const endTriage = require('./configRepo/.github/scripts/auto-triage/end.js');
              await endTriage({ github, context, core })

        - name: 🥳 Success
          run: echo Triage has completed successfully!
           