# This is a basic lable syncing action configured by /.github/utils/label-config.json

name: 🏷️ Manual Label Sync

on:
  workflow_dispatch:

permissions:
  issues: write

jobs:
  sync-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Sync labels from config
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const labels = JSON.parse(fs.readFileSync('.github/utils/label-config.json', 'utf8'));

            for (const label of labels) {
              try {
                await github.rest.issues.getLabel({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  name: label.name
                });

                // If it exists, update:
                await github.rest.issues.updateLabel({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  name: label.name,
                  color: label.color,
                  description: label.description
                });

                console.log(`✅ Updated label: ${label.name}`);
              } catch (error) {
                if (error.status === 404) {
                  // Create if it doesn't exist:
                  await github.rest.issues.createLabel({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    name: label.name,
                    color: label.color,
                    description: label.description
                  });

                  console.log(`➕ Created label: ${label.name}`);
                } else {
                  throw error;
                }
              }
            }
