name: "New Pull Request"
on:
  pull_request:
    types: [opened, reopened, ready_for_review]

jobs:
  use-comment:
    uses: SessionsBot/.github/workflow-templates/new-PR-comment.yml@main
    permissions:
      pull-requests: write
      issues: write